### ISSUE TITLE
Increase Pacdot visibility

### ISSUE THREAD

**Issue by jleung51** [pacmacro/pm-android#12]
The current Pacdots can often be difficult to see, especially when hidden by text from the maps. A more contrasting appearance would greatly help visibility, as well as being able to quickly check which Pacdots have already been eaten.

**Comment by landalex** [comment]
What style do you think would help with contrast? Would making the borders ticker help, or do you want the colors to change?

**Comment by jleung51** [comment]
Perhaps make them larger and with a yellow fill? I don't think we need to make the borders flicker, as they already flash slightly upon each update.

**Comment by landalex** [comment]
I meant thicker, not ticker, my bad.

**Comment by jleung51** [comment]
Oh - then I think thicker borders would help as well, yes.

**Comment by jleung51** [comment]
Completed with pull request #37.
