### ISSUE TITLE
Reduce frequency of polling

### ISSUE THREAD

**Issue by landalex** [pacmacro/pm-android#21]
In an effort to reduce the amount of data used, the game should request server updates less frequently and send updates less frequently.

**Comment by jleung51** [comment]
@landalex Are you able to find time to finish this within the next week?

**Comment by landalex** [comment]
I'll try to have it done by Monday (August 27th).

**Comment by landalex** [comment]
Fixed with 4587dd2ec3d448b2f4dfb0abf256a9e6043a3a98
