### ISSUE TITLE
Re-format credit screen

### ISSUE THREAD

**Issue by laurens777** [pacmacro/pm-android#23]
Re-format the credit screen so it scales properly on all devices.

**Comment by jleung51** [comment]
Examples of inconsistently formatted content:

## My Phone ![screenshot_20190201-175733](https://user-images.githubusercontent.com/9059549/52158691-d0458680-264f-11e9-80c7-dfacdb51381b.png)

## Celina's Phone ![51496141_397212427513655_7776693190316261376_n](https://user-images.githubusercontent.com/9059549/52158706-e4898380-264f-11e9-8158-0fd25528aadb.jpg)

**Comment by subin216** [comment]
After reformat credit screen

480 * 800 hdpi (Nexus One)
<img width="212" alt="Screen Shot 2019-05-23 at 10 27 46 AM" src="https://user-images.githubusercontent.com/34588197/58273371-70c9ce80-7d45-11e9-9dcc-86ca330e57da.png">

720 * 1280 xhdpi (Galaxy Nexus)
<img width="212" alt="Screen Shot 2019-05-23 at 10 28 20 AM" src="https://user-images.githubusercontent.com/34588197/58273398-83dc9e80-7d45-11e9-8623-17d59cd02bf2.png">

1080 * 1920 xxhdpi (Nexus5)
<img width="214" alt="Screen Shot 2019-05-23 at 10 29 20 AM" src="https://user-images.githubusercontent.com/34588197/58273510-b8e8f100-7d45-11e9-89e4-66f63693da1c.png">

**Comment by subin216** [comment]
sent a full-request with the error: Fix Google Maps API compatibility error #28 together

**Comment by jleung51** [comment]
Resolved by the above-referenced commit.
