### ISSUE TITLE
Fix Google Maps API compatibility error

### ISSUE THREAD

**Issue by jleung51** [pacmacro/pm-android#28]
When opening the app on my Google Pixel 1, an error is shown about the API compatibility.

![Screenshot_20190308-133901](https://user-images.githubusercontent.com/9059549/54174941-21624a80-4446-11e9-9099-fa7417784cdc.png)

**Comment by subin216** [comment]
Related Link:
https://developer.android.com/distribute/best-practices/develop/restrictions-non-sdk-interfaces
https://android-developers.googleblog.com/2018/02/improving-stability-by-reducing-usage.html

Temporary Solution:
change buildToolsVersion to "28.0.1" and targetSdkVersion to 28 in build.gradle(Module: app)

**Comment by subin216** [comment]
Related Link:
https://developer.android.com/distribute/best-practices/develop/restrictions-non-sdk-interfaces
https://android-developers.googleblog.com/2018/02/improving-stability-by-reducing-usage.html

Solution:
change targetSdkVersion to 28 in build.gradle(Module: app)

**Comment by subin216** [comment]
Currently, our **compileSdkVersion** 26 and **targetSdkVersion** is 28.
Android doesn't recommend that compileSdkVersion is lower than targetSdkVersion (not error but warning). But, I didn't change compileSdkVersion yet since I thought it would be too much changes.
Please consider this.

**Comment by jleung51** [comment]
Resolved by the above-referenced commit.
