### ISSUE TITLE
Service runs when app is closed

### ISSUE THREAD

**Issue by landalex** [pacmacro/pm-android#4]

**Comment by laurens777** [comment]
Hi is this still an issue? If so can you elaborate?

**Comment by landalex** [comment]
I didn't do a very good job of describing the issue, obviously, and it's been a while but I think the problem was that the app could be closed manually (Home button -> Recents -> Swipe it away) but the service would continue to run in the background. Fixing this would mean making sure that the service either 1) closes when the app is killed (maybe hard to do) or 2) has an easy way of stopping the service through a button on the notification.

**Comment by jleung51** [comment]
Issue resolved in above-referenced commit.
