### ISSUE TITLE
Fetch game state

### ISSUE THREAD

**Issue by landalex** [pacmacro/pm-android#9]
Get game state from server, and modify the game accordingly.

For example, actions for each state would be:
1. Initializing
    - Display status on map, and in lobby/playeractivity
2. In progress
    - Change nothing
3. Paused
    - Display paused message on all screens
4. Pacman wins
    - Show message on all screens, end game loop
5. Ghosts win
    - Same as Pacman wins

**Comment by jleung51** [comment]
Combined with issue #13.
